ARG ORACLE_VERSION=$ORACLE_VERSION
ARG FORTANIX_PKCS11_VERSION=$FORTANIX_PKCS11_VERSION
FROM herdus0512/demo-images:oracle-$ORACLE_VERSION

bash:
  CMD ["/bin/bash"]
  SAVE IMAGE oracle-bash:$ORACLE_VERSION

db:
  USER root
  ARG SDKMS_API_ENDPOINT=$SDKMS_API_ENDPOINT
  WORKDIR /app
  COPY scripts /app
  RUN --no-cache mkdir -p /etc/fortanix
  RUN --no-cache chown oracle:oinstall /etc/fortanix
  RUN --no-cache chmod -R 755 /etc/fortanix
  COPY scripts /app
  RUN --no-cache ./gen_conf.sh
  RUN --no-cache wget https://s3.us-west-1.amazonaws.com/downloads.fortanix.com/4.2.1500/fortanix_pkcs11_4.2.1500.so
  RUN --no-cache mkdir -p /opt/oracle/extapi/64/hsm/fortanix/4.2.1500
  RUN --no-cache cp /app/fortanix_pkcs11_4.2.1500.so /opt/oracle/extapi/64/hsm/fortanix/4.2.1500/libpkcs11.so
  RUN --no-cache chmod -R 755 /opt/oracle
  RUN --no-cache chown -R oracle:dba /opt/oracle

  RUN --no-cache cp /app/inject_api_key.sh /docker-entrypoint-initdb.d/

  USER oracle
  WORKDIR /home/oracle

  ENTRYPOINT /app/docker-entrypoint.sh
  
  SAVE IMAGE oracle-db:$ORACLE_VERSION
