ARG ORACLE_VERSION=$ORACLE_VERSION
ARG FORTANIX_PKCS11_VERSION=$FORTANIX_PKCS11_VERSION
FROM herdus0512/demo-images:oracle-$ORACLE_VERSION

bash:
  CMD ["/bin/bash"]
  SAVE IMAGE oracle-bash:$ORACLE_VERSION

db:
  USER root
  WORKDIR /app
  RUN --no-cache sudo mkdir -p /etc/fortanix
  COPY --chown=root:root scripts/pkcs11.conf /etc/fortanix/
  RUN --no-cache sudo wget https://s3.us-west-1.amazonaws.com/downloads.fortanix.com/4.2.1500/fortanix_pkcs11_4.2.1500.so
  RUN --no-cache sudo mkdir -p /opt/oracle/extapi/64/hsm/fortanix/4.2.1500
  RUN --no-cache sudo cp /app/fortanix_pkcs11_4.2.1500.so /opt/oracle/extapi/64/hsm/fortanix/4.2.1500/libpkcs11.so
  RUN --no-cache sudo chmod -R 755 /opt/oracle
  RUN --no-cache sudo chown -R oracle:oinstall /opt/oracle
  SAVE IMAGE oracle-db:$ORACLE_VERSION

tde:
  WORKDIR /app
  ARG SDKMS_MONGO_APP_ID=$SDKMS_MONGO_APP_ID
  ARG SDKMS_API_ENDPOINT=$SDKMS_API_ENDPOINT
  ARG SDKMS_API_USERNAME=$SDKMS_API_USERNAME
  ARG SDKMS_API_PASSWORD=$SDKMS_API_PASSWORD
  ARG SDKMS_ACCT_ID=$SDKMS_ACCT_ID
  COPY scripts /app
  RUN --no-cache ./gen_cert.sh
  CMD ["/usr/bin/mongod","--enableEncryption","--kmipServerName","$SDKMS_API_ENDPOINT","--kmipServerCAFile","/app/DSM_Chain_CA.pem","--kmipClientCertificateFile","/app/client.pem"]
  SAVE IMAGE mongodb-db:$MONGO_VERSION
