ARG MONGO_VERSION=$MONGO_VERSION
FROM herdus0512/demo-images:mongodb-$MONGO_VERSION

bash:
  CMD ["/bin/bash"]
  SAVE IMAGE mongodb-bash:$MONGO_VERSION

db:
  CMD ["/usr/bin/mongod"]
  SAVE IMAGE mongodb-db:$MONGO_VERSION

tde:
  WORKDIR /app
  ENV SDKMS_APP_ID=$SDKMS_MONGO_APP_ID
  ARG SDKMS_API_ENDPOINT=$SDKMS_API_ENDPOINT
  ARG SDKMS_API_USERNAME=$SDKMS_API_USERNAME
  ARG SDKMS_API_PASSWORD=$SDKMS_API_PASSWORD
  ARG SDKMS_ACCT_ID=$SDKMS_ACCT_ID
  COPY scripts /app
  RUN --no-cache ./gen_cert.sh
  CMD ["/usr/bin/mongod","--enableEncryption","--kmipServerName","$SDKMS_API_ENDPOINT","--kmipServerCAFile","/app/DSM_Chain_CA.pem","--kmipClientCertificateFile","/app/client.pem"]
  SAVE IMAGE mongodb-db:$MONGO_VERSION