ARG VERSION=$VERSION
FROM herdus0512/demo-images:mongodb-$VERSION

bash:
  RUN --interactive /bin/bash

db:
  RUN --interactive /usr/bin/mongod

db-tde:
  WORKDIR /app
  ARG SDKMS_APP_ID=$SDKMS_APP_ID
  ARG SDKMS_API_ENDPOINT=$SDKMS_API_ENDPOINT
  ARG SDKMS_API_USERNAME=$SDKMS_API_USERNAME
  ARG SDKMS_API_PASSWORD=$SDKMS_API_PASSWORD
  ARG SDKMS_ACCT_ID=$SDKMS_ACCT_ID
  COPY scripts /app
  RUN --no-cache ./gen_cert.sh
  RUN --interactive /usr/bin/mongod --enableEncryption --kmipServerName $SDKMS_API_ENDPOINT --kmipServerCAFile /app/DSM_Chain_CA.pem --kmipClientCertificateFile /app/client.pem
